"""Initial migration

Revision ID: 09c5e5b69e87
Revises:
Create Date: 2026-02-11 21:04:38.934732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09c5e5b69e87"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "OAI_PMH",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_name", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("namespace_identifier", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ROAR",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_name", sa.String(length=500), nullable=False),
        sa.Column("home_page", sa.String(length=500), nullable=False),
        sa.Column("oai_pmh", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("repository_url", sa.String(length=500), nullable=False),
        sa.Column("repository_names", sa.ARRAY(sa.String(length=500)), nullable=False),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_item_evaluated", sa.String(length=20), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Record")
    op.drop_table("ROAR")
    op.drop_table("OAI_PMH")
    # ### end Alembic commands ###
