"""add indexes and fix mutable types

Revision ID: dcf153d2d326
Revises: 09c5e5b69e87
Create Date: 2026-08-20 20:02:26.890324

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dcf153d2d326"
down_revision: Union[str, Sequence[str], None] = "09c5e5b69e87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_record_is_completed", "Record", ["is_completed"], unique=False)
    op.create_index(
        "ix_record_last_item_evaluated", "Record", ["last_item_evaluated"], unique=False
    )
    op.create_index(
        "ix_record_repository_url", "Record", ["repository_url"], unique=False
    )
    op.create_index("ix_record_updated_at", "Record", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_record_updated_at", table_name="Record")
    op.drop_index("ix_record_repository_url", table_name="Record")
    op.drop_index("ix_record_last_item_evaluated", table_name="Record")
    op.drop_index("ix_record_is_completed", table_name="Record")
    # ### end Alembic commands ###
