"""empty message

Revision ID: 9e7249944468
Revises: 7419693945f2
Create Date: 2021-10-14 20:13:00.443537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e7249944468'
down_revision = '7419693945f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Record',
    sa.Column('token', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('repository_names', sa.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('last_item_evaluated', sa.String(length=20), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Record')
    # ### end Alembic commands ###
